#!/usr/bin/env bash
# One-time bootstrap for the Ubuntu EC2 instance. Run as the 'ubuntu' user
# (the account GitHub Actions will SSH in as):
#
#   scp -i wnmr.pem deploy/setup-ec2.sh deploy/transitops.service \
#     ubuntu@<EC2_HOST>:~
#   ssh -i wnmr.pem ubuntu@<EC2_HOST> 'chmod +x setup-ec2.sh && ./setup-ec2.sh'
#
# Installs Node.js, Docker (for Postgres later), Nginx, creates the deploy
# directory + /etc/nginx/ssl (for the Cloudflare Origin CA cert you generate
# in the Cloudflare dashboard and copy in by hand), a user-level systemd
# service, and enables lingering. The domain is proxied through Cloudflare,
# so TLS between Cloudflare and this box uses a Cloudflare Origin CA cert,
# not Certbot/Let's Encrypt — see deploy/README.md.
set -euo pipefail

DEPLOY_PATH="$HOME/transitops"
SERVICE_NAME="transitops"

echo "==> Updating apt"
sudo apt-get update -y

echo "==> Installing Node.js 20 (NodeSource)"
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install -y nodejs

echo "==> Installing rsync + nginx"
sudo apt-get install -y rsync nginx

echo "==> Installing Docker (for Postgres / ml-service later)"
if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sudo sh
  sudo usermod -aG docker "$USER"
fi
sudo apt-get install -y docker-compose-plugin

echo "==> Creating deploy directory: $DEPLOY_PATH"
mkdir -p "$DEPLOY_PATH"

echo "==> Fetching current Cloudflare IP ranges for Nginx real_ip config"
sudo mkdir -p /etc/nginx/ssl
{
  echo "# Auto-generated by setup-ec2.sh — Cloudflare IP ranges"
  echo "# Re-run this script (or refresh manually) if Cloudflare rotates ranges:"
  echo "# https://www.cloudflare.com/ips/"
  for ip in $(curl -fsSL https://www.cloudflare.com/ips-v4); do
    echo "set_real_ip_from $ip;"
  done
  for ip in $(curl -fsSL https://www.cloudflare.com/ips-v6); do
    echo "set_real_ip_from $ip;"
  done
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} | sudo tee /etc/nginx/conf.d/cloudflare-realip.conf > /dev/null

echo "==> Installing user-level systemd service"
mkdir -p "$HOME/.config/systemd/user"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/transitops.service" ]; then
  cp "$SCRIPT_DIR/transitops.service" "$HOME/.config/systemd/user/${SERVICE_NAME}.service"
elif [ -f "$HOME/transitops.service" ]; then
  cp "$HOME/transitops.service" "$HOME/.config/systemd/user/${SERVICE_NAME}.service"
else
  echo "ERROR: transitops.service not found next to this script or in \$HOME"
  exit 1
fi

systemctl --user daemon-reload
systemctl --user enable "$SERVICE_NAME"

echo "==> Enabling lingering so the service survives logout/reboot"
sudo loginctl enable-linger "$(whoami)"

echo ""
echo "Bootstrap complete."
echo ""
echo "Notes:"
echo "  - Log out and back in (or reboot) once so the 'docker' group applies."
echo "  - The '${SERVICE_NAME}' service stays idle until a root package.json"
echo "    with 'npm start' exists in $DEPLOY_PATH — expected while scaffolding."
echo "  - Next: GitHub secrets EC2_HOST + EC2_SSH_KEY, a Cloudflare Origin CA"
echo "    cert copied to /etc/nginx/ssl/, then DNS + nginx site"
echo "    (see deploy/README.md)."
